name: First workflows

on: 
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Print a welcome message
      run: echo "welcome first message"

    - name: Checkout repository
      uses: actions/checkout@v6.0.1

    - name: List repository files
      run: ls -la

    
